/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {

    public static void main(String[] args) {

        BitMap bmp = new BitMap(args[0]);
        System.out.println("Hello World!");
    }
}
